### ISSUE TITLE
Compilação Windows bash

### ISSUE THREAD

**Issue by LucasMonari** [DaviAragao/primos#1]
Ao compilar utilizando o Bash do Windows 10, o compilador não encontra o `mpi.h`

**Comment by DaviAragao** [comment]
Obrigado por relatar o problema LucasMonari. Qual compilador está usando?

**Comment by LucasMonari** [comment]
GCC

**Comment by DaviAragao** [comment]
Você precisa instalar mpich2 em seu windows. Estou atualizando o README.md, mas enquanto isso pode ver [aqui](http://swash.sourceforge.net/online_doc/swashimp/node9.html) mais detalhes da instalação da biblioteca em seu sistema operacional.

**Comment by DaviAragao** [comment]
As novas versões do software suportam apenas clusters com sistemas operacionais unuix-like.
